const root = document.documentElement;

// ── Shared utilities ───────────────────────────────────────────────────────

const proxySources = [
    'https://api.allorigins.win/raw?url=',
    'https://corsproxy.io/?',
    'https://api.codetabs.com/v1/proxy?quest=',
];

function getTimeAgo(dateStr) {
    const date = new Date(dateStr);
    if (isNaN(date)) return '';
    const seconds = Math.floor((new Date() - date) / 1000);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(seconds / 3600);
    if (minutes < 1) return 'Just now';
    if (minutes < 60) return `${minutes}m`;
    if (hours < 24) return `${hours}H`;
    return `${Math.floor(hours / 24)}D`;
}

// ── Theme ──────────────────────────────────────────────────────────────────

const applyProfileTheme = (theme) => {
    if (!theme) return;

    const { bg = '#111111', fg = '#ffffff' } = theme;

    const r = parseInt(fg.slice(1, 3), 16);
    const g = parseInt(fg.slice(3, 5), 16);
    const b = parseInt(fg.slice(5, 7), 16);

    root.style.setProperty('--theme-bg',       bg);
    root.style.setProperty('--theme-fg',       fg);
    root.style.setProperty('--theme-fg-64',    `rgba(${r}, ${g}, ${b}, 0.64)`);
    root.style.setProperty('--theme-fg-5',     `rgba(${r}, ${g}, ${b}, 0.05)`);
    root.style.setProperty('--link-underline', `rgba(${r}, ${g}, ${b}, 0.3)`);
};

// Fetches profile.json, applies the first space's theme, and returns the
// full profile so callers can read feeds, preferences, etc.
async function loadAndApplyTheme() {
    try {
        const res = await fetch('profile.json');
        if (!res.ok) throw new Error('profile.json not found');
        const profile = await res.json();
        const activeIndex = parseInt(localStorage.getItem('activeSpaceIndex') || '0', 10);

        // Merge user-added feeds stored in localStorage
        profile.spaces?.forEach((space, i) => {
            const extra = JSON.parse(localStorage.getItem(`extraFeeds_${i}`) || '[]');
            if (extra.length) space.feeds = [...(space.feeds || []), ...extra];
        });

        const activeSpace = profile.spaces?.[activeIndex] || profile.spaces?.[0];
        if (activeSpace?.theme) applyProfileTheme(activeSpace.theme);
        return profile;
    } catch (e) {
        console.error('Theme: could not load profile.json', e);
        return null;
    }
}

// ── Article content post-processing ───────────────────────────────────────

const SUMMARY_PATTERNS = [
    /^summary (created|generated|written|provided) by/i,
    /^ai[- ]generated/i,
    /^generated by/i,
    /^powered by/i,
    /^this summary/i,
    /^auto[- ]summarized/i,
];

const processArticleContent = (container) => {
    if (!container) return;

    const savedData = JSON.parse(sessionStorage.getItem('currentPostData'));
    const authorName = savedData?.author?.trim();

    container.querySelectorAll('p').forEach(p => {
        const text = p.textContent.trim();
        const wordCount = text.split(/\s+/).filter(Boolean).length;

        if (authorName && text.toLowerCase().startsWith(authorName.toLowerCase())) {
            p.style.display = 'none';
            return;
        }

        if (SUMMARY_PATTERNS.some(re => re.test(text))) {
            p.setAttribute('data-summary-label', '');
            return;
        }

        // 1–4 word paragraphs with no sentence-ending punctuation are treated as labels/captions
        if (wordCount >= 1 && wordCount <= 4 && !/[.!?]$/.test(text)) {
            p.setAttribute('data-label', '');
        }
    });
};

// Exposed so article-reader.js can call it after injecting content
window.processArticleContent = processArticleContent;

// ── Sidebar button ────────────────────────────────────────────────────────

const sidebarBtn = document.querySelector('#sidebar-btn');
if (sidebarBtn) sidebarBtn.addEventListener('click', () => window.location.href = 'sidebar.html');

// ── Reload button ──────────────────────────────────────────────────────────

const refreshButton = document.querySelector('.reload');

if (refreshButton) {
    refreshButton.addEventListener('click', () => {
        window.scrollTo({ top: 0, behavior: 'smooth' });

        const checkScroll = setInterval(() => {
            if (window.scrollY === 0) {
                clearInterval(checkScroll);
                location.reload();
            }
        }, 100);
    });
}
