const root = document.documentElement;

// ── Theme application ──────────────────────────────────────────────────────

const applyProfileTheme = (theme) => {
  if (!theme) return;

  root.style.setProperty('--base-h', theme['base-hue']);
  root.style.setProperty('--saturation', theme['saturation'] + '%');
  root.style.setProperty('--lightness-offset', theme['lightness']);

  updateTextColor();
};

const updateTextColor = () => {
  const style = getComputedStyle(root);
  const offset = parseFloat(style.getPropertyValue('--lightness-offset'));
  const baseH = style.getPropertyValue('--base-h').trim();
  const sat = style.getPropertyValue('--saturation').trim();

  // Derive perceived lightness more accurately:
  // offset > 0  → light background → dark text
  // offset <= 0 → dark background  → light text
  // We also interpolate text contrast so near-zero offsets don't look washed out.

  if (offset > 0) {
    // Light bg — use dark text derived from the hue for cohesion
    const textL = Math.round(10 + offset * 15); // 10–25% lightness
    root.style.setProperty('--text-color-100', `hsl(${baseH}, ${sat}, ${textL}%)`);
    root.style.setProperty('--text-color-65',  `hsla(${baseH}, ${sat}, ${textL}%, 0.6)`);
    root.style.setProperty('--text-color-50',  `hsla(${baseH}, ${sat}, ${textL}%, 0.25)`);
    root.style.setProperty('--link-underline',  `hsla(${baseH}, ${sat}, ${textL}%, 0.35)`);
  } else {
    // Dark bg — white text, adjusted opacity based on how dark it is
    // Very dark (offset near -1) needs full white; near 0 can be slightly softer
    const alpha65 = offset < -0.5 ? 0.7 : 0.6;
    const alpha50 = offset < -0.5 ? 0.45 : 0.35;
    root.style.setProperty('--text-color-100', 'hsl(0, 0%, 100%)');
    root.style.setProperty('--text-color-65',  `hsla(0, 0%, 100%, ${alpha65})`);
    root.style.setProperty('--text-color-50',  `hsla(0, 0%, 100%, ${alpha50})`);
    root.style.setProperty('--link-underline',  `hsla(0, 0%, 100%, 0.3)`);
  }
};

// ── Article content post-processing ───────────────────────────────────────
// Called after article HTML is injected into .article-content

const SUMMARY_PATTERNS = [
  /^summary (created|generated|written|provided) by/i,
  /^ai[- ]generated/i,
  /^generated by/i,
  /^powered by/i,
  /^this summary/i,
  /^auto[- ]summarized/i,
];

const processArticleContent = (container) => {
  if (!container) return;

  // Retrieve author name from session storage
  const savedData = JSON.parse(sessionStorage.getItem('currentPostData'));
  const authorName = savedData?.author?.trim();

  const paragraphs = container.querySelectorAll('p');

  paragraphs.forEach(p => {
    const text = p.textContent.trim();
    const wordCount = text.split(/\s+/).filter(Boolean).length;

    // 1. Hide paragraphs starting with the author's name
    if (authorName && text.toLowerCase().startsWith(authorName.toLowerCase())) {
      p.style.display = 'none';
      return;
    }

    // 2. Hide "summary created by …" labels
    if (SUMMARY_PATTERNS.some(re => re.test(text))) {
      p.setAttribute('data-summary-label', '');
      return;
    }

    // 3. Short label detection: 1–4 words, no sentence punctuation
    if (
      wordCount >= 1 &&
      wordCount <= 4 &&
      !/[.!?]$/.test(text)
    ) {
      p.setAttribute('data-label', '');
    }
  });
};

// Expose so article-reader.js can call it after injecting content
window.processArticleContent = processArticleContent;

